import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'gallery_screen.dart';

void main() async {
  // 1. Ensure Flutter binding is initialized before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Initialize Firebase
  // Note: For a production app, you should use DefaultFirebaseOptions.currentPlatform
  // generated by the flutterfire CLI (`flutterfire configure`). 
  // We wrap it in try-catch to avoid app crashing if google-services.json is missing during testing.
  try {
    await Firebase.initializeApp();
    debugPrint('Firebase initialized successfully');
  } catch (e) {
    debugPrint('Firebase initialization error: $e');
    debugPrint('Please ensure you have configured Firebase correctly with flutterfire CLI.');
  }
  
  // 3. Run the App
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase Gallery',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.light,
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.deepPurple,
          foregroundColor: Colors.white,
          centerTitle: true,
          elevation: 2,
        ),
        floatingActionButtonTheme: const FloatingActionButtonThemeData(
          backgroundColor: Colors.deepPurple,
          foregroundColor: Colors.white,
        ),
        useMaterial3: true, // Use modern Material 3 design
      ),
      home: const GalleryScreen(),
    );
  }
}
